apiVersion: schema.esdm.io/core/v1
kind: command
name: mark-copy-on-loan
description: Internal command emitted by sync-copy-on-checkout policy.
scope:
  domain: public-library
  boundedContext: cataloging
  aggregate: book-copy
data:
  type: object
  required: [barcode]
  properties:
    barcode:
      type: string
publishes:
  - copy-status-changed

---
apiVersion: schema.esdm.io/core/v1
kind: command
name: mark-copy-available
description: Internal command emitted by sync-copy-on-checkin policy.
scope:
  domain: public-library
  boundedContext: cataloging
  aggregate: book-copy
data:
  type: object
  required: [barcode]
  properties:
    barcode:
      type: string
publishes:
  - copy-status-changed
